#!/bin/bash
# Simplified short CelebA-HQ 256 sweep.
#
# Stable path only:
# - single-node jobs
# - 16x16 latent grid
# - real-valued coefficients (no variational coefficient posterior)
# - fixed sparsity / embedding dim
# - stronger VQGAN-style backbone with a wider continuous latent
# - broad layout x dictionary-size matrix for cluster-wide fanout

set -euo pipefail

LEGACY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$LEGACY_DIR/../../.." && pwd)"
BASE_SWEEP="$LEGACY_DIR/sweep_celebahq256_vqgan_cap.sh"

if [[ ! -x "$BASE_SWEEP" ]]; then
  echo "Missing base sweep launcher: $BASE_SWEEP" >&2
  exit 1
fi

STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)}"
PARTITION="${PARTITION:-gpu-redhat}"
TIME_LIMIT="${TIME_LIMIT:-24:00:00}"
GPUS="${GPUS:-3}"
CPUS="${CPUS:-24}"
MEM_MB="${MEM_MB:-240000}"
EXCLUDE_NODES="${EXCLUDE_NODES:-gpu043}"

STAGE1_EPOCHS="${STAGE1_EPOCHS:-5}"
STAGE2_EPOCHS="${STAGE2_EPOCHS:-5}"

NUM_DOWNSAMPLES="${NUM_DOWNSAMPLES:-4}"
EXPECTED_LATENT_SIDE="${EXPECTED_LATENT_SIDE:-16}"
BATCH_SIZE="${BATCH_SIZE:-1}"
STAGE2_BATCH_SIZE="${STAGE2_BATCH_SIZE:-1}"

STAGE1_LR="${STAGE1_LR:-2.5e-4}"
DICT_LR="${DICT_LR:-3.0e-4}"
WARMUP_STEPS="${WARMUP_STEPS:-500}"
MIN_LR_RATIO="${MIN_LR_RATIO:-0.05}"
STAGE2_LR="${STAGE2_LR:-3.0e-4}"
STAGE2_WARMUP_STEPS="${STAGE2_WARMUP_STEPS:-500}"
STAGE2_MIN_LR_RATIO="${STAGE2_MIN_LR_RATIO:-0.05}"

DEFAULT_NUM_HIDDENS="${DEFAULT_NUM_HIDDENS:-160}"
DEFAULT_NUM_RES_BLOCKS="${DEFAULT_NUM_RES_BLOCKS:-3}"
DEFAULT_NUM_RES_HIDDENS="${DEFAULT_NUM_RES_HIDDENS:-96}"
CHANNEL_MULTIPLIERS="${CHANNEL_MULTIPLIERS:-[1,1,2,4,4]}"
ATTN_RESOLUTIONS="${ATTN_RESOLUTIONS:-[32,16,8]}"
BACKBONE_LATENT_CHANNELS="${BACKBONE_LATENT_CHANNELS:-160}"
DECODER_EXTRA_RESIDUAL_LAYERS="${DECODER_EXTRA_RESIDUAL_LAYERS:-2}"
USE_MID_ATTENTION="${USE_MID_ATTENTION:-true}"

PERCEPTUAL_WEIGHT="${PERCEPTUAL_WEIGHT:-0.0}"
S1_ENABLE_VAL_LATENT_VISUALS="${S1_ENABLE_VAL_LATENT_VISUALS:-false}"
S1_LOG_IMAGES_EVERY="${S1_LOG_IMAGES_EVERY:-200}"
S1_DIAG_LOG_INTERVAL="${S1_DIAG_LOG_INTERVAL:-200}"
S1_VAL_CHECK_INTERVAL="${S1_VAL_CHECK_INTERVAL:-1.0}"
S1_COMPUTE_FID="${S1_COMPUTE_FID:-false}"

COEFF_BINS="${COEFF_BINS:-0}"
STAGE1_VARIATIONAL_COEFFS="${STAGE1_VARIATIONAL_COEFFS:-false}"
AR_COEFF_LOSS_TYPE="${AR_COEFF_LOSS_TYPE:-recon_mse}"
AR_COEFF_LOSS_WEIGHT="${AR_COEFF_LOSS_WEIGHT:-0.1}"
AR_SAMPLE_COEFF_MODE="${AR_SAMPLE_COEFF_MODE:-mean}"
AR_AUTOREGRESSIVE_COEFFS="${AR_AUTOREGRESSIVE_COEFFS:-true}"
S2_SAMPLE_EVERY_N_EPOCHS="${S2_SAMPLE_EVERY_N_EPOCHS:-1}"
S2_LOG_RECON_EVERY_N_STEPS="${S2_LOG_RECON_EVERY_N_STEPS:-200}"

PATCH_SPARSITY_LEVEL="${PATCH_SPARSITY_LEVEL:-24}"
PATCH_EMBEDDING_DIM="${PATCH_EMBEDDING_DIM:-16}"
PATCH_CASE_FILTER="${PATCH_CASE_FILTER:-p2s2_k24_d4k,p4s4_k24_d4k,p8s8_k24_d4k,p4s2h_k24_d4k,p8s4h_k24_d4k}"
NOPATCH_CASE_FILTER="${NOPATCH_CASE_FILTER:-nopatch_k16_d4k}"
DICT_SIZES="${DICT_SIZES:-4096 8192 16384 32768}"

echo "[Simple5] partition=$PARTITION gpus_per_job=$GPUS epochs=${STAGE1_EPOCHS}/${STAGE2_EPOCHS}"
echo "[Simple5] latent=${EXPECTED_LATENT_SIDE}x${EXPECTED_LATENT_SIDE} patch_k=$PATCH_SPARSITY_LEVEL patch_d=$PATCH_EMBEDDING_DIM"
echo "[Simple5] patch_cases=$PATCH_CASE_FILTER"
echo "[Simple5] nopatch_case=$NOPATCH_CASE_FILTER"
echo "[Simple5] dictionary_sizes=$DICT_SIZES"

submitted_groups=0
for dict_size in $DICT_SIZES; do
  out_root="${OUT_ROOT_BASE:-/scratch/$USER/runs}/celebahq256_simple5_k${dict_size}_${STAMP}"
  run_prefix="chq256s5_k${dict_size}"
  job_prefix="chq5k${dict_size}"
  echo "[Simple5] launching K=$dict_size -> $out_root"

  env \
    PARTITION="$PARTITION" \
    TIME_LIMIT="$TIME_LIMIT" \
    NODES=1 \
    GPUS="$GPUS" \
    CPUS="$CPUS" \
    MEM_MB="$MEM_MB" \
    EXCLUDE_NODES="$EXCLUDE_NODES" \
    OUT_ROOT="$out_root" \
    RUN_PREFIX="$run_prefix" \
    JOB_PREFIX="$job_prefix" \
    STAGE1_EPOCHS="$STAGE1_EPOCHS" \
    STAGE2_EPOCHS="$STAGE2_EPOCHS" \
    NUM_DOWNSAMPLES="$NUM_DOWNSAMPLES" \
    EXPECTED_LATENT_SIDE="$EXPECTED_LATENT_SIDE" \
    BATCH_SIZE="$BATCH_SIZE" \
    STAGE2_BATCH_SIZE="$STAGE2_BATCH_SIZE" \
    STAGE1_LR="$STAGE1_LR" \
    DICT_LR="$DICT_LR" \
    WARMUP_STEPS="$WARMUP_STEPS" \
    MIN_LR_RATIO="$MIN_LR_RATIO" \
    STAGE2_LR="$STAGE2_LR" \
    STAGE2_WARMUP_STEPS="$STAGE2_WARMUP_STEPS" \
    STAGE2_MIN_LR_RATIO="$STAGE2_MIN_LR_RATIO" \
    DEFAULT_NUM_HIDDENS="$DEFAULT_NUM_HIDDENS" \
    DEFAULT_NUM_RES_BLOCKS="$DEFAULT_NUM_RES_BLOCKS" \
    DEFAULT_NUM_RES_HIDDENS="$DEFAULT_NUM_RES_HIDDENS" \
    CHANNEL_MULTIPLIERS="$CHANNEL_MULTIPLIERS" \
    ATTN_RESOLUTIONS="$ATTN_RESOLUTIONS" \
    BACKBONE_LATENT_CHANNELS="$BACKBONE_LATENT_CHANNELS" \
    DECODER_EXTRA_RESIDUAL_LAYERS="$DECODER_EXTRA_RESIDUAL_LAYERS" \
    USE_MID_ATTENTION="$USE_MID_ATTENTION" \
    PERCEPTUAL_WEIGHT="$PERCEPTUAL_WEIGHT" \
    S1_ENABLE_VAL_LATENT_VISUALS="$S1_ENABLE_VAL_LATENT_VISUALS" \
    S1_LOG_IMAGES_EVERY="$S1_LOG_IMAGES_EVERY" \
    S1_DIAG_LOG_INTERVAL="$S1_DIAG_LOG_INTERVAL" \
    S1_VAL_CHECK_INTERVAL="$S1_VAL_CHECK_INTERVAL" \
    S1_COMPUTE_FID="$S1_COMPUTE_FID" \
    COEFF_BINS="$COEFF_BINS" \
    STAGE1_VARIATIONAL_COEFFS="$STAGE1_VARIATIONAL_COEFFS" \
    AR_COEFF_LOSS_TYPE="$AR_COEFF_LOSS_TYPE" \
    AR_COEFF_LOSS_WEIGHT="$AR_COEFF_LOSS_WEIGHT" \
    AR_SAMPLE_COEFF_MODE="$AR_SAMPLE_COEFF_MODE" \
    AR_AUTOREGRESSIVE_COEFFS="$AR_AUTOREGRESSIVE_COEFFS" \
    S2_SAMPLE_EVERY_N_EPOCHS="$S2_SAMPLE_EVERY_N_EPOCHS" \
    S2_LOG_RECON_EVERY_N_STEPS="$S2_LOG_RECON_EVERY_N_STEPS" \
    OVERRIDE_NUM_EMBEDDINGS="$dict_size" \
    OVERRIDE_SPARSITY_LEVEL="$PATCH_SPARSITY_LEVEL" \
    OVERRIDE_EMBEDDING_DIM="$PATCH_EMBEDDING_DIM" \
    CASE_FILTER="$PATCH_CASE_FILTER" \
    bash "$BASE_SWEEP"

  env \
    PARTITION="$PARTITION" \
    TIME_LIMIT="$TIME_LIMIT" \
    NODES=1 \
    GPUS="$GPUS" \
    CPUS="$CPUS" \
    MEM_MB="$MEM_MB" \
    EXCLUDE_NODES="$EXCLUDE_NODES" \
    OUT_ROOT="$out_root" \
    RUN_PREFIX="$run_prefix" \
    JOB_PREFIX="$job_prefix" \
    STAGE1_EPOCHS="$STAGE1_EPOCHS" \
    STAGE2_EPOCHS="$STAGE2_EPOCHS" \
    NUM_DOWNSAMPLES="$NUM_DOWNSAMPLES" \
    EXPECTED_LATENT_SIDE="$EXPECTED_LATENT_SIDE" \
    BATCH_SIZE="$BATCH_SIZE" \
    STAGE2_BATCH_SIZE="$STAGE2_BATCH_SIZE" \
    STAGE1_LR="$STAGE1_LR" \
    DICT_LR="$DICT_LR" \
    WARMUP_STEPS="$WARMUP_STEPS" \
    MIN_LR_RATIO="$MIN_LR_RATIO" \
    STAGE2_LR="$STAGE2_LR" \
    STAGE2_WARMUP_STEPS="$STAGE2_WARMUP_STEPS" \
    STAGE2_MIN_LR_RATIO="$STAGE2_MIN_LR_RATIO" \
    DEFAULT_NUM_HIDDENS="$DEFAULT_NUM_HIDDENS" \
    DEFAULT_NUM_RES_BLOCKS="$DEFAULT_NUM_RES_BLOCKS" \
    DEFAULT_NUM_RES_HIDDENS="$DEFAULT_NUM_RES_HIDDENS" \
    CHANNEL_MULTIPLIERS="$CHANNEL_MULTIPLIERS" \
    ATTN_RESOLUTIONS="$ATTN_RESOLUTIONS" \
    BACKBONE_LATENT_CHANNELS="$BACKBONE_LATENT_CHANNELS" \
    DECODER_EXTRA_RESIDUAL_LAYERS="$DECODER_EXTRA_RESIDUAL_LAYERS" \
    USE_MID_ATTENTION="$USE_MID_ATTENTION" \
    PERCEPTUAL_WEIGHT="$PERCEPTUAL_WEIGHT" \
    S1_ENABLE_VAL_LATENT_VISUALS="$S1_ENABLE_VAL_LATENT_VISUALS" \
    S1_LOG_IMAGES_EVERY="$S1_LOG_IMAGES_EVERY" \
    S1_DIAG_LOG_INTERVAL="$S1_DIAG_LOG_INTERVAL" \
    S1_VAL_CHECK_INTERVAL="$S1_VAL_CHECK_INTERVAL" \
    S1_COMPUTE_FID="$S1_COMPUTE_FID" \
    COEFF_BINS="$COEFF_BINS" \
    STAGE1_VARIATIONAL_COEFFS="$STAGE1_VARIATIONAL_COEFFS" \
    AR_COEFF_LOSS_TYPE="$AR_COEFF_LOSS_TYPE" \
    AR_COEFF_LOSS_WEIGHT="$AR_COEFF_LOSS_WEIGHT" \
    AR_SAMPLE_COEFF_MODE="$AR_SAMPLE_COEFF_MODE" \
    AR_AUTOREGRESSIVE_COEFFS="$AR_AUTOREGRESSIVE_COEFFS" \
    S2_SAMPLE_EVERY_N_EPOCHS="$S2_SAMPLE_EVERY_N_EPOCHS" \
    S2_LOG_RECON_EVERY_N_STEPS="$S2_LOG_RECON_EVERY_N_STEPS" \
    OVERRIDE_NUM_EMBEDDINGS="$dict_size" \
    CASE_FILTER="$NOPATCH_CASE_FILTER" \
    bash "$BASE_SWEEP"

  submitted_groups=$((submitted_groups + 1))
done

echo "[Simple5] submitted $submitted_groups groups from $BASE_SWEEP"
