#!/bin/bash

set -euo pipefail
unset LC_ALL || true
export LANG=C


ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JOB_NAME="${JOB_NAME:-proto-rqsd-8g-mn}"
PARTITION="${PARTITION:-auto}"
NODES="${NODES:-2}"
GPUS_PER_NODE="${GPUS_PER_NODE:-4}"
TOTAL_GPUS="$((NODES * GPUS_PER_NODE))"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
MEM_MB="${MEM_MB:-128000}"
TIME_LIMIT="${TIME_LIMIT:-24:00:00}"
DATA_DIR="${DATA_DIR:-/cache/home/xl598/Projects/data/celeba}"
IMAGE_SIZE="${IMAGE_SIZE:-128}"
OUT_DIR="${OUT_DIR:-/scratch/$USER/runs/laser_celeba${IMAGE_SIZE}_quantized}"
IMAGE="${IMAGE:-docker://pytorch/pytorch:2.4.1-cuda12.1-cudnn9-runtime}"
PYTHONUSERBASE_DIR="${PYTHONUSERBASE_DIR:-/scratch/$USER/.pydeps/proto_rqsd_py311}"
STAGE1_EPOCHS="${STAGE1_EPOCHS:-10}"
STAGE2_EPOCHS="${STAGE2_EPOCHS:-10}"
STAGE1_SOURCE_CKPT="${STAGE1_SOURCE_CKPT:-}"
STAGE1_AUTO_RESUME_FROM_LATEST="${STAGE1_AUTO_RESUME_FROM_LATEST:-false}"
STAGE1_CHECKPOINT_EVERY_STEPS="${STAGE1_CHECKPOINT_EVERY_STEPS:-0}"
REBUILD_TOKEN_CACHE="${REBUILD_TOKEN_CACHE:-false}"
STAGE2_SOURCE_RUN="${STAGE2_SOURCE_RUN:-}"
STAGE2_SOURCE_TOKEN_CACHE="${STAGE2_SOURCE_TOKEN_CACHE:-}"
STAGE2_SOURCE_CKPT="${STAGE2_SOURCE_CKPT:-}"
STAGE1_LR="${STAGE1_LR:-1.6e-3}"
STAGE2_LR="${STAGE2_LR:-8e-3}"
STAGE1_LR_SCHEDULE="${STAGE1_LR_SCHEDULE:-cosine}"
STAGE1_WARMUP_EPOCHS="${STAGE1_WARMUP_EPOCHS:-1}"
STAGE1_MIN_LR_RATIO="${STAGE1_MIN_LR_RATIO:-0.1}"
STAGE1_DICT_OPTIMIZER="${STAGE1_DICT_OPTIMIZER:-shared_adam}"
STAGE1_DICT_LR_MULTIPLIER="${STAGE1_DICT_LR_MULTIPLIER:-1.0}"
STAGE1_DICT_LR_SCHEDULE="${STAGE1_DICT_LR_SCHEDULE:-cosine}"
STAGE1_DICT_WARMUP_EPOCHS="${STAGE1_DICT_WARMUP_EPOCHS:-1}"
STAGE1_DICT_MIN_LR_RATIO="${STAGE1_DICT_MIN_LR_RATIO:-0.05}"
STAGE1_DICT_GRAD_CLIP="${STAGE1_DICT_GRAD_CLIP:-0.1}"
STAGE1_DICT_MAX_UPDATE_NORM="${STAGE1_DICT_MAX_UPDATE_NORM:-0.0}"
STAGE1_LOSS_SPIKE_SKIP_RATIO="${STAGE1_LOSS_SPIKE_SKIP_RATIO:-0.0}"
STAGE1_LOSS_EMA_BETA="${STAGE1_LOSS_EMA_BETA:-0.98}"
BOTTLENECK_WEIGHT="${BOTTLENECK_WEIGHT:-1.0}"
GRAD_CLIP="${GRAD_CLIP:-1.0}"
STAGE1_BOTTLENECK_WEIGHT_START="${STAGE1_BOTTLENECK_WEIGHT_START:-1.0}"
STAGE1_BOTTLENECK_WARMUP_EPOCHS="${STAGE1_BOTTLENECK_WARMUP_EPOCHS:-0}"
STAGE1_DICT_LOSS_WEIGHT="${STAGE1_DICT_LOSS_WEIGHT:-nan}"
STAGE1_DICT_LOSS_WEIGHT_START="${STAGE1_DICT_LOSS_WEIGHT_START:-nan}"
STAGE1_DICT_LOSS_WARMUP_EPOCHS="${STAGE1_DICT_LOSS_WARMUP_EPOCHS:-0}"
STAGE1_COMMITMENT_LOSS_WEIGHT="${STAGE1_COMMITMENT_LOSS_WEIGHT:-nan}"
STAGE1_COMMITMENT_LOSS_WEIGHT_START="${STAGE1_COMMITMENT_LOSS_WEIGHT_START:-nan}"
STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS="${STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS:-0}"
STAGE1_AMP="${STAGE1_AMP:-true}"
STAGE1_AMP_DTYPE="${STAGE1_AMP_DTYPE:-auto}"
STAGE1_COHERENCE_WEIGHT="${STAGE1_COHERENCE_WEIGHT:-0.0}"
STAGE1_COHERENCE_WEIGHT_START="${STAGE1_COHERENCE_WEIGHT_START:-nan}"
STAGE1_COHERENCE_WARMUP_EPOCHS="${STAGE1_COHERENCE_WARMUP_EPOCHS:-0}"
STAGE1_COHERENCE_MARGIN="${STAGE1_COHERENCE_MARGIN:-0.0}"
STAGE2_WARMUP_STEPS="${STAGE2_WARMUP_STEPS:-500}"
STAGE2_MIN_LR_RATIO="${STAGE2_MIN_LR_RATIO:-0.01}"
STAGE2_WEIGHT_DECAY="${STAGE2_WEIGHT_DECAY:-0.01}"
STAGE2_SCHED_SAMPLING_FINAL_PROB="${STAGE2_SCHED_SAMPLING_FINAL_PROB:-0.0}"
BATCH_SIZE="${BATCH_SIZE:-32}"
STAGE2_BATCH_SIZE="${STAGE2_BATCH_SIZE:-32}"
NUM_WORKERS="${NUM_WORKERS:-8}"
TOKEN_NUM_WORKERS="${TOKEN_NUM_WORKERS:-0}"
TOKEN_SUBSET="${TOKEN_SUBSET:-0}"
RFID_NUM_SAMPLES="${RFID_NUM_SAMPLES:-0}"
STAGE2_FID_NUM_SAMPLES="${STAGE2_FID_NUM_SAMPLES:-0}"
STAGE2_FID_EVERY_EPOCHS="${STAGE2_FID_EVERY_EPOCHS:-0}"
STAGE2_SAMPLE_EVERY_STEPS="${STAGE2_SAMPLE_EVERY_STEPS:-2000}"
STAGE2_SAMPLE_BATCH_SIZE="${STAGE2_SAMPLE_BATCH_SIZE:-32}"
STAGE2_SAMPLE_CANDIDATE_FACTOR="${STAGE2_SAMPLE_CANDIDATE_FACTOR:-4}"
STAGE2_SAMPLE_TEMPERATURE="${STAGE2_SAMPLE_TEMPERATURE:-0.5}"
STAGE2_SAMPLE_TOP_K="${STAGE2_SAMPLE_TOP_K:-0}"
STAGE2_SAMPLE_COEFF_TEMPERATURE="${STAGE2_SAMPLE_COEFF_TEMPERATURE:-nan}"
STAGE2_SAMPLE_COEFF_MODE="${STAGE2_SAMPLE_COEFF_MODE:-gaussian}"
STAGE2_SAMPLE_QUALITY_WEIGHT="${STAGE2_SAMPLE_QUALITY_WEIGHT:-1.0}"
STAGE2_SAMPLE_BRIGHTNESS_WEIGHT="${STAGE2_SAMPLE_BRIGHTNESS_WEIGHT:-1.0}"
STAGE2_SAMPLE_OVERBRIGHT_WEIGHT="${STAGE2_SAMPLE_OVERBRIGHT_WEIGHT:-1.0}"
STAGE2_SAMPLE_REJECT_DARK_Z="${STAGE2_SAMPLE_REJECT_DARK_Z:-1.5}"
STAGE2_SAMPLE_REJECT_BRIGHT_Z="${STAGE2_SAMPLE_REJECT_BRIGHT_Z:-1.5}"
STAGE2_SAMPLE_SORT_BY_QUALITY="${STAGE2_SAMPLE_SORT_BY_QUALITY:-true}"
STAGE2_SAMPLE_IMAGE_SIZE="${STAGE2_SAMPLE_IMAGE_SIZE:-$IMAGE_SIZE}"
STAGE2_AUTOREGRESSIVE_COEFFS="${STAGE2_AUTOREGRESSIVE_COEFFS:-true}"
QUANTIZE_SPARSE_COEFFS="${QUANTIZE_SPARSE_COEFFS:-true}"
VARIATIONAL_COEFFS="${VARIATIONAL_COEFFS:-false}"
VARIATIONAL_COEFF_KL_WEIGHT="${VARIATIONAL_COEFF_KL_WEIGHT:-1e-3}"
VARIATIONAL_COEFF_PRIOR_STD="${VARIATIONAL_COEFF_PRIOR_STD:-0.25}"
VARIATIONAL_COEFF_MIN_STD="${VARIATIONAL_COEFF_MIN_STD:-0.01}"
AE_NUM_DOWNSAMPLES="${AE_NUM_DOWNSAMPLES:-4}"
EMBEDDING_DIM="${EMBEDDING_DIM:-16}"
NUM_HIDDENS="${NUM_HIDDENS:-128}"
NUM_RES_HIDDENS="${NUM_RES_HIDDENS:-32}"
NUM_RES_LAYERS="${NUM_RES_LAYERS:-2}"
NUM_ATOMS="${NUM_ATOMS:-1024}"
SPARSITY_LEVEL="${SPARSITY_LEVEL:-8}"
N_BINS="${N_BINS:-2048}"
COMMITMENT_COST="${COMMITMENT_COST:-0.25}"
COEF_MAX="${COEF_MAX:-20.0}"
COEF_QUANTIZATION="${COEF_QUANTIZATION:-uniform}"
COEF_MU="${COEF_MU:-0.0}"
PATCH_BASED="${PATCH_BASED:-false}"
PATCH_SIZE="${PATCH_SIZE:-4}"
PATCH_STRIDE="${PATCH_STRIDE:-2}"
PATCH_RECONSTRUCTION="${PATCH_RECONSTRUCTION:-center_crop}"
STAGE2_ARCH="${STAGE2_ARCH:-spatial_depth}"
TF_D_MODEL="${TF_D_MODEL:-512}"
TF_HEADS="${TF_HEADS:-8}"
TF_LAYERS="${TF_LAYERS:-12}"
TF_FF="${TF_FF:-1024}"
TF_DROPOUT="${TF_DROPOUT:-0.1}"
TF_GLOBAL_TOKENS="${TF_GLOBAL_TOKENS:-0}"
if [[ -z "${STAGE2_COEFF_LOSS_TYPE+x}" ]]; then
  if [[ "${VARIATIONAL_COEFFS}" == "1" || "${VARIATIONAL_COEFFS}" == "true" || "${VARIATIONAL_COEFFS}" == "TRUE" || "${VARIATIONAL_COEFFS}" == "yes" || "${VARIATIONAL_COEFFS}" == "YES" ]]; then
    STAGE2_COEFF_LOSS_TYPE="gaussian_nll"
  elif [[ "${PATCH_BASED}" == "1" || "${PATCH_BASED}" == "true" || "${PATCH_BASED}" == "TRUE" || "${PATCH_BASED}" == "yes" || "${PATCH_BASED}" == "YES" ]]; then
    STAGE2_COEFF_LOSS_TYPE="mse"
  elif [[ "${QUANTIZE_SPARSE_COEFFS}" == "0" || "${QUANTIZE_SPARSE_COEFFS}" == "false" || "${QUANTIZE_SPARSE_COEFFS}" == "FALSE" || "${QUANTIZE_SPARSE_COEFFS}" == "no" || "${QUANTIZE_SPARSE_COEFFS}" == "NO" ]]; then
    STAGE2_COEFF_LOSS_TYPE="mse"
  else
    STAGE2_COEFF_LOSS_TYPE="gt_atom_recon_mse"
  fi
fi
WANDB_MODE="${WANDB_MODE:-online}"
WANDB_PROJECT="${WANDB_PROJECT:-laser-scratch}"
WANDB_NAME="${WANDB_NAME:-proto_rqsd_${TOTAL_GPUS}gpu_mn_s${STAGE1_EPOCHS}_s2${STAGE2_EPOCHS}}"
LOG_PREFIX="${LOG_PREFIX:-proto_rqsd_${TOTAL_GPUS}g_mn}"
WANDB_API_KEY_FILE="${WANDB_API_KEY_FILE:-/scratch/$USER/.secrets/wandb_api_key}"
DIST_TIMEOUT_MINUTES="${DIST_TIMEOUT_MINUTES:-180}"
ENTRYPOINT="${ENTRYPOINT:-proto.py}"
SBATCH_DEPENDENCY="${SBATCH_DEPENDENCY:-}"
RECIPE_PROFILE="${RECIPE_PROFILE:-}"
RUN_TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

apply_recipe_profile() {
  case "${1:-}" in
    ""|"none")
      return 0
      ;;
    "415ephb2")
      STAGE1_EPOCHS="5"
      STAGE2_EPOCHS="5"
      STAGE1_SOURCE_CKPT=""
      REBUILD_TOKEN_CACHE="false"
      STAGE1_LR="2e-4"
      STAGE2_LR="1e-3"
      STAGE1_LR_SCHEDULE="cosine"
      STAGE1_WARMUP_EPOCHS="2"
      STAGE1_MIN_LR_RATIO="0.1"
      STAGE1_DICT_OPTIMIZER="separate_sgd"
      STAGE1_DICT_LR_MULTIPLIER="0.25"
      STAGE1_DICT_LR_SCHEDULE="cosine"
      STAGE1_DICT_WARMUP_EPOCHS="2"
      STAGE1_DICT_MIN_LR_RATIO="0.05"
      STAGE1_DICT_GRAD_CLIP="0.05"
      STAGE1_DICT_MAX_UPDATE_NORM="0.0"
      STAGE1_LOSS_SPIKE_SKIP_RATIO="0.0"
      STAGE1_LOSS_EMA_BETA="0.98"
      BOTTLENECK_WEIGHT="1.0"
      GRAD_CLIP="1.0"
      STAGE1_BOTTLENECK_WEIGHT_START="1.0"
      STAGE1_BOTTLENECK_WARMUP_EPOCHS="0"
      STAGE2_WARMUP_STEPS="500"
      STAGE2_MIN_LR_RATIO="0.01"
      STAGE2_WEIGHT_DECAY="0.01"
      BATCH_SIZE="32"
      STAGE2_BATCH_SIZE="32"
      NUM_WORKERS="8"
      TOKEN_NUM_WORKERS="4"
      TOKEN_SUBSET="98304"
      STAGE2_SAMPLE_EVERY_STEPS="1000"
      STAGE2_SAMPLE_BATCH_SIZE="32"
      STAGE2_SAMPLE_CANDIDATE_FACTOR="4"
      STAGE2_SAMPLE_TEMPERATURE="0.5"
      STAGE2_SAMPLE_TOP_K="0"
      STAGE2_SAMPLE_COEFF_TEMPERATURE="nan"
      STAGE2_SAMPLE_COEFF_MODE="gaussian"
      STAGE2_SAMPLE_QUALITY_WEIGHT="1.0"
      STAGE2_SAMPLE_BRIGHTNESS_WEIGHT="1.0"
      STAGE2_SAMPLE_OVERBRIGHT_WEIGHT="1.0"
      STAGE2_SAMPLE_REJECT_DARK_Z="1.5"
      STAGE2_SAMPLE_REJECT_BRIGHT_Z="1.5"
      STAGE2_SAMPLE_SORT_BY_QUALITY="true"
      STAGE2_SAMPLE_IMAGE_SIZE="128"
      QUANTIZE_SPARSE_COEFFS="true"
      AE_NUM_DOWNSAMPLES="4"
      COEF_MAX="20.0"
      ;;
    *)
      echo "Unsupported RECIPE_PROFILE: ${1}" >&2
      echo "Supported values: 415ephb2" >&2
      exit 1
      ;;
  esac
}

apply_recipe_profile "$RECIPE_PROFILE"

if [[ ! -d "$DATA_DIR" ]]; then
  echo "Missing data directory: $DATA_DIR" >&2
  exit 1
fi

auto_select_gpu_partition() {
  if [[ -n "${PARTITION:-}" && "${PARTITION}" != "auto" ]]; then
    return 0
  fi
  local best_partition=""
  local best_idle=-1
  while read -r partition avail timelimit nodes _; do
    [[ -z "${partition:-}" || "$partition" == "PARTITION" ]] && continue
    partition="${partition%\*}"
    case "$partition" in
      gpu|gpu-redhat|cgpu)
        ;;
      *)
        continue
        ;;
    esac
    local alloc idle other total
    IFS='/' read -r alloc idle other total <<< "$nodes"
    if [[ "$idle" =~ ^[0-9]+$ ]] && (( idle > best_idle )); then
      best_idle="$idle"
      best_partition="$partition"
    fi
  done < <(sinfo -s 2>/dev/null)
  if [[ -z "$best_partition" ]]; then
    best_partition="gpu-redhat"
    best_idle=0
  fi
  PARTITION="$best_partition"
  export PARTITION
  echo "[Launch] auto-selected PARTITION=$PARTITION (idle_nodes=$best_idle)"
}

auto_select_gpu_partition

SBATCH_EXTRA_ARGS=()
if [[ -n "$SBATCH_DEPENDENCY" ]]; then
  SBATCH_EXTRA_ARGS+=(--dependency="$SBATCH_DEPENDENCY")
fi

if [[ ! -f "$ROOT_DIR/$ENTRYPOINT" ]]; then
  echo "Missing $ENTRYPOINT under $ROOT_DIR" >&2
  exit 1
fi

SBATCH_CMD=(sbatch)
if ((${#SBATCH_EXTRA_ARGS[@]} > 0)); then
  SBATCH_CMD+=("${SBATCH_EXTRA_ARGS[@]}")
fi

"${SBATCH_CMD[@]}" \
  --partition="$PARTITION" \
  --requeue \
  --job-name="$JOB_NAME" \
  --nodes="$NODES" \
  --ntasks-per-node="$GPUS_PER_NODE" \
  --cpus-per-task="$CPUS_PER_TASK" \
  --gres="gpu:${GPUS_PER_NODE}" \
  --mem="$MEM_MB" \
  --time="$TIME_LIMIT" \
  --chdir="$ROOT_DIR" \
  --output="$ROOT_DIR/${LOG_PREFIX}_%j.out" \
  --error="$ROOT_DIR/${LOG_PREFIX}_%j.err" \
  --wrap='set -euo pipefail
unset LC_ALL || true
export LANG=C
export PYTHONUNBUFFERED=1
export NCCL_DEBUG=INFO
export TORCH_DISTRIBUTED_DEBUG=DETAIL
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
USER_NAME=$(id -un)
PROJECT_DIR='"$ROOT_DIR"'
DATA_DIR='"$DATA_DIR"'
OUT_DIR='"$OUT_DIR"'
IMAGE='"$IMAGE"'
PYTHONUSERBASE_DIR='"$PYTHONUSERBASE_DIR"'
PYTHON_SITE="$PYTHONUSERBASE_DIR/lib/python3.11/site-packages"
RUN_TIMESTAMP='"$RUN_TIMESTAMP"'
STAGE1_EPOCHS='"$STAGE1_EPOCHS"'
STAGE2_EPOCHS='"$STAGE2_EPOCHS"'
STAGE1_SOURCE_CKPT='"$STAGE1_SOURCE_CKPT"'
STAGE1_AUTO_RESUME_FROM_LATEST='"$STAGE1_AUTO_RESUME_FROM_LATEST"'
STAGE1_CHECKPOINT_EVERY_STEPS='"$STAGE1_CHECKPOINT_EVERY_STEPS"'
REBUILD_TOKEN_CACHE='"$REBUILD_TOKEN_CACHE"'
STAGE2_SOURCE_RUN='"$STAGE2_SOURCE_RUN"'
STAGE2_SOURCE_TOKEN_CACHE='"$STAGE2_SOURCE_TOKEN_CACHE"'
STAGE2_SOURCE_CKPT='"$STAGE2_SOURCE_CKPT"'
STAGE1_LR='"$STAGE1_LR"'
STAGE2_LR='"$STAGE2_LR"'
STAGE1_LR_SCHEDULE='"$STAGE1_LR_SCHEDULE"'
STAGE1_WARMUP_EPOCHS='"$STAGE1_WARMUP_EPOCHS"'
STAGE1_MIN_LR_RATIO='"$STAGE1_MIN_LR_RATIO"'
STAGE1_DICT_OPTIMIZER='"$STAGE1_DICT_OPTIMIZER"'
STAGE1_DICT_LR_MULTIPLIER='"$STAGE1_DICT_LR_MULTIPLIER"'
STAGE1_DICT_LR_SCHEDULE='"$STAGE1_DICT_LR_SCHEDULE"'
STAGE1_DICT_WARMUP_EPOCHS='"$STAGE1_DICT_WARMUP_EPOCHS"'
STAGE1_DICT_MIN_LR_RATIO='"$STAGE1_DICT_MIN_LR_RATIO"'
STAGE1_DICT_GRAD_CLIP='"$STAGE1_DICT_GRAD_CLIP"'
STAGE1_DICT_MAX_UPDATE_NORM='"$STAGE1_DICT_MAX_UPDATE_NORM"'
STAGE1_LOSS_SPIKE_SKIP_RATIO='"$STAGE1_LOSS_SPIKE_SKIP_RATIO"'
STAGE1_LOSS_EMA_BETA='"$STAGE1_LOSS_EMA_BETA"'
GRAD_CLIP='"$GRAD_CLIP"'
BOTTLENECK_WEIGHT='"$BOTTLENECK_WEIGHT"'
STAGE1_BOTTLENECK_WEIGHT_START='"$STAGE1_BOTTLENECK_WEIGHT_START"'
STAGE1_BOTTLENECK_WARMUP_EPOCHS='"$STAGE1_BOTTLENECK_WARMUP_EPOCHS"'
STAGE1_DICT_LOSS_WEIGHT='"$STAGE1_DICT_LOSS_WEIGHT"'
STAGE1_DICT_LOSS_WEIGHT_START='"$STAGE1_DICT_LOSS_WEIGHT_START"'
STAGE1_DICT_LOSS_WARMUP_EPOCHS='"$STAGE1_DICT_LOSS_WARMUP_EPOCHS"'
STAGE1_COMMITMENT_LOSS_WEIGHT='"$STAGE1_COMMITMENT_LOSS_WEIGHT"'
STAGE1_COMMITMENT_LOSS_WEIGHT_START='"$STAGE1_COMMITMENT_LOSS_WEIGHT_START"'
STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS='"$STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS"'
STAGE1_AMP='"$STAGE1_AMP"'
STAGE1_AMP_DTYPE='"$STAGE1_AMP_DTYPE"'
STAGE1_COHERENCE_WEIGHT='"$STAGE1_COHERENCE_WEIGHT"'
STAGE1_COHERENCE_WEIGHT_START='"$STAGE1_COHERENCE_WEIGHT_START"'
STAGE1_COHERENCE_WARMUP_EPOCHS='"$STAGE1_COHERENCE_WARMUP_EPOCHS"'
STAGE1_COHERENCE_MARGIN='"$STAGE1_COHERENCE_MARGIN"'
STAGE2_WARMUP_STEPS='"$STAGE2_WARMUP_STEPS"'
STAGE2_MIN_LR_RATIO='"$STAGE2_MIN_LR_RATIO"'
STAGE2_WEIGHT_DECAY='"$STAGE2_WEIGHT_DECAY"'
STAGE2_SCHED_SAMPLING_FINAL_PROB='"$STAGE2_SCHED_SAMPLING_FINAL_PROB"'
STAGE2_COEFF_LOSS_TYPE='"$STAGE2_COEFF_LOSS_TYPE"'
BATCH_SIZE='"$BATCH_SIZE"'
STAGE2_BATCH_SIZE='"$STAGE2_BATCH_SIZE"'
NUM_WORKERS='"$NUM_WORKERS"'
TOKEN_NUM_WORKERS='"$TOKEN_NUM_WORKERS"'
TOKEN_SUBSET='"$TOKEN_SUBSET"'
RFID_NUM_SAMPLES='"$RFID_NUM_SAMPLES"'
STAGE2_FID_NUM_SAMPLES='"$STAGE2_FID_NUM_SAMPLES"'
STAGE2_FID_EVERY_EPOCHS='"$STAGE2_FID_EVERY_EPOCHS"'
STAGE2_SAMPLE_EVERY_STEPS='"$STAGE2_SAMPLE_EVERY_STEPS"'
STAGE2_SAMPLE_BATCH_SIZE='"$STAGE2_SAMPLE_BATCH_SIZE"'
STAGE2_SAMPLE_CANDIDATE_FACTOR='"$STAGE2_SAMPLE_CANDIDATE_FACTOR"'
STAGE2_SAMPLE_TEMPERATURE='"$STAGE2_SAMPLE_TEMPERATURE"'
STAGE2_SAMPLE_TOP_K='"$STAGE2_SAMPLE_TOP_K"'
STAGE2_SAMPLE_COEFF_TEMPERATURE='"$STAGE2_SAMPLE_COEFF_TEMPERATURE"'
STAGE2_SAMPLE_COEFF_MODE='"$STAGE2_SAMPLE_COEFF_MODE"'
STAGE2_SAMPLE_QUALITY_WEIGHT='"$STAGE2_SAMPLE_QUALITY_WEIGHT"'
STAGE2_SAMPLE_BRIGHTNESS_WEIGHT='"$STAGE2_SAMPLE_BRIGHTNESS_WEIGHT"'
STAGE2_SAMPLE_OVERBRIGHT_WEIGHT='"$STAGE2_SAMPLE_OVERBRIGHT_WEIGHT"'
STAGE2_SAMPLE_REJECT_DARK_Z='"$STAGE2_SAMPLE_REJECT_DARK_Z"'
STAGE2_SAMPLE_REJECT_BRIGHT_Z='"$STAGE2_SAMPLE_REJECT_BRIGHT_Z"'
STAGE2_SAMPLE_SORT_BY_QUALITY='"$STAGE2_SAMPLE_SORT_BY_QUALITY"'
STAGE2_SAMPLE_IMAGE_SIZE='"$STAGE2_SAMPLE_IMAGE_SIZE"'
STAGE2_AUTOREGRESSIVE_COEFFS='"$STAGE2_AUTOREGRESSIVE_COEFFS"'
QUANTIZE_SPARSE_COEFFS='"$QUANTIZE_SPARSE_COEFFS"'
VARIATIONAL_COEFFS='"$VARIATIONAL_COEFFS"'
VARIATIONAL_COEFF_KL_WEIGHT='"$VARIATIONAL_COEFF_KL_WEIGHT"'
VARIATIONAL_COEFF_PRIOR_STD='"$VARIATIONAL_COEFF_PRIOR_STD"'
VARIATIONAL_COEFF_MIN_STD='"$VARIATIONAL_COEFF_MIN_STD"'
AE_NUM_DOWNSAMPLES='"$AE_NUM_DOWNSAMPLES"'
EMBEDDING_DIM='"$EMBEDDING_DIM"'
NUM_HIDDENS='"$NUM_HIDDENS"'
NUM_RES_HIDDENS='"$NUM_RES_HIDDENS"'
NUM_RES_LAYERS='"$NUM_RES_LAYERS"'
NUM_ATOMS='"$NUM_ATOMS"'
SPARSITY_LEVEL='"$SPARSITY_LEVEL"'
N_BINS='"$N_BINS"'
COMMITMENT_COST='"$COMMITMENT_COST"'
COEF_MAX='"$COEF_MAX"'
COEF_QUANTIZATION='"$COEF_QUANTIZATION"'
COEF_MU='"$COEF_MU"'
PATCH_BASED='"$PATCH_BASED"'
PATCH_SIZE='"$PATCH_SIZE"'
PATCH_STRIDE='"$PATCH_STRIDE"'
PATCH_RECONSTRUCTION='"$PATCH_RECONSTRUCTION"'
STAGE2_ARCH='"$STAGE2_ARCH"'
TF_D_MODEL='"$TF_D_MODEL"'
TF_HEADS='"$TF_HEADS"'
TF_LAYERS='"$TF_LAYERS"'
TF_FF='"$TF_FF"'
TF_DROPOUT='"$TF_DROPOUT"'
TF_GLOBAL_TOKENS='"$TF_GLOBAL_TOKENS"'
WANDB_MODE='"$WANDB_MODE"'
WANDB_PROJECT='"$WANDB_PROJECT"'
WANDB_NAME='"$WANDB_NAME"'
WANDB_API_KEY_FILE='"$WANDB_API_KEY_FILE"'
DIST_TIMEOUT_MINUTES='"$DIST_TIMEOUT_MINUTES"'
ENTRYPOINT='"$ENTRYPOINT"'
MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
MASTER_PORT=$((29000 + SLURM_JOB_ID % 1000))
if ! command -v module >/dev/null 2>&1; then
  if [[ -f /etc/profile.d/modules.sh ]]; then
    set +u
    source /etc/profile.d/modules.sh
    set -u
  elif [[ -f /usr/share/Modules/init/bash ]]; then
    set +u
    source /usr/share/Modules/init/bash
    set -u
  fi
fi
if ! command -v singularity >/dev/null 2>&1; then
  if command -v module >/dev/null 2>&1; then
    module load singularity 2>/dev/null || true
    module load singularityce 2>/dev/null || true
    module load singularity-ce 2>/dev/null || true
  fi
fi
command -v singularity >/dev/null 2>&1 || { echo singularity_not_found >&2; exit 1; }
mkdir -p "$OUT_DIR" "$PYTHONUSERBASE_DIR" "$(dirname "$WANDB_API_KEY_FILE")"
JOB_PROJECT_DIR="$OUT_DIR/source_snapshot_${SLURM_JOB_ID}"
mkdir -p "$JOB_PROJECT_DIR"
# Stage a stable per-job source snapshot before launching ranks in the container.
rsync -a --delete \
  --exclude '.git/' \
  --exclude '__pycache__/' \
  --exclude '.tmp/' \
  --exclude '.tmp_*' \
  --exclude '*.out' \
  --exclude '*.err' \
  --exclude 'cluster_logs/' \
  --exclude 'resamples/' \
  --exclude 'wandb/' \
  --exclude 'pre_variation_snapshot_fc5ecd3/' \
  "$PROJECT_DIR/" "$JOB_PROJECT_DIR/"
PROJECT_DIR="$JOB_PROJECT_DIR"
export WANDB_API_KEY_FILE
export SINGULARITYENV_WANDB_API_KEY_FILE="$WANDB_API_KEY_FILE"
export APPTAINERENV_WANDB_API_KEY_FILE="$WANDB_API_KEY_FILE"
unset WANDB_API_KEY || true
unset SINGULARITYENV_WANDB_API_KEY || true
unset APPTAINERENV_WANDB_API_KEY || true
export PYTHONUSERBASE="$PYTHONUSERBASE_DIR"
export PYTHONNOUSERSITE=0
export PYTHONPATH="$PYTHON_SITE${PYTHONPATH:+:$PYTHONPATH}"
export MASTER_ADDR MASTER_PORT
if ! PYTHONUSERBASE="$PYTHONUSERBASE_DIR" PYTHONNOUSERSITE=0 PYTHONPATH="$PYTHON_SITE${PYTHONPATH:+:$PYTHONPATH}" singularity exec --bind "$PROJECT_DIR" --bind "/scratch/$USER_NAME" --bind "$DATA_DIR" --bind "$OUT_DIR" "$IMAGE" python3 - <<'PY_DEP' >/dev/null 2>&1
import importlib
import scipy
import torch_fidelity
module = importlib.import_module("wandb")
raise SystemExit(0 if hasattr(module, "init") and hasattr(module, "Api") else 1)
PY_DEP
then
  PYTHONUSERBASE="$PYTHONUSERBASE_DIR" PYTHONNOUSERSITE=0 PYTHONPATH="$PYTHON_SITE${PYTHONPATH:+:$PYTHONPATH}" singularity exec --bind "$PROJECT_DIR" --bind "/scratch/$USER_NAME" --bind "$DATA_DIR" --bind "$OUT_DIR" "$IMAGE" python3 -m pip install --user scipy wandb torch-fidelity
fi
RUNNER="$OUT_DIR/slurm_proto_multinode_${SLURM_JOB_ID}.sh"
cat > "$RUNNER" <<EOF_RUNNER
#!/bin/bash
set -euo pipefail
unset LC_ALL || true
export LANG=C
export RANK="\$SLURM_PROCID"
export WORLD_SIZE="\$SLURM_NTASKS"
export LOCAL_RANK="\$SLURM_LOCALID"
export MASTER_ADDR="${MASTER_ADDR}"
export MASTER_PORT="${MASTER_PORT}"
export PROTO_LAUNCH_TIMESTAMP="${RUN_TIMESTAMP}"
export PROTO_RUN_SLURM_JOB_ID="${SLURM_JOB_ID}"
export PROTO_RUN_ID="slurm-\${SLURM_JOB_ID}-${RUN_TIMESTAMP}"
export WANDB_RUN_ID="\${PROTO_RUN_ID}"
export PYTHONUSERBASE="${PYTHONUSERBASE_DIR}"
export PYTHONNOUSERSITE=0
export PYTHONPATH="${PYTHON_SITE}\${PYTHONPATH:+:\$PYTHONPATH}"
export WANDB_API_KEY_FILE="${WANDB_API_KEY_FILE}"
if [[ -f "\${WANDB_API_KEY_FILE}" ]]; then
  IFS= read -r WANDB_API_KEY < "\${WANDB_API_KEY_FILE}" || true
  export WANDB_API_KEY
fi
CMD=(
  python3 "${PROJECT_DIR}/${ENTRYPOINT}"
  --dataset celeba
  --data_dir "${DATA_DIR}"
  --image_size "${IMAGE_SIZE}"
  --out_dir "${OUT_DIR}"
  --dist_timeout_minutes "${DIST_TIMEOUT_MINUTES}"
  --stage1_epochs "${STAGE1_EPOCHS}"
  --stage1_checkpoint_every_steps "${STAGE1_CHECKPOINT_EVERY_STEPS}"
  --stage2_epochs "${STAGE2_EPOCHS}"
  --stage1_lr "${STAGE1_LR}"
  --stage2_lr "${STAGE2_LR}"
  --stage1_lr_schedule "${STAGE1_LR_SCHEDULE}"
  --stage1_warmup_epochs "${STAGE1_WARMUP_EPOCHS}"
  --stage1_min_lr_ratio "${STAGE1_MIN_LR_RATIO}"
  --stage1_dict_optimizer "${STAGE1_DICT_OPTIMIZER}"
  --stage1_dict_lr_multiplier "${STAGE1_DICT_LR_MULTIPLIER}"
  --stage1_dict_lr_schedule "${STAGE1_DICT_LR_SCHEDULE}"
  --stage1_dict_warmup_epochs "${STAGE1_DICT_WARMUP_EPOCHS}"
  --stage1_dict_min_lr_ratio "${STAGE1_DICT_MIN_LR_RATIO}"
  --stage1_dict_grad_clip "${STAGE1_DICT_GRAD_CLIP}"
  --stage1_dict_max_update_norm "${STAGE1_DICT_MAX_UPDATE_NORM}"
  --stage1_loss_spike_skip_ratio "${STAGE1_LOSS_SPIKE_SKIP_RATIO}"
  --stage1_loss_ema_beta "${STAGE1_LOSS_EMA_BETA}"
  --bottleneck_weight "${BOTTLENECK_WEIGHT}"
  --grad_clip "${GRAD_CLIP}"
  --stage1_bottleneck_weight_start "${STAGE1_BOTTLENECK_WEIGHT_START}"
  --stage1_bottleneck_warmup_epochs "${STAGE1_BOTTLENECK_WARMUP_EPOCHS}"
  --stage1_dict_loss_weight "${STAGE1_DICT_LOSS_WEIGHT}"
  --stage1_dict_loss_weight_start "${STAGE1_DICT_LOSS_WEIGHT_START}"
  --stage1_dict_loss_warmup_epochs "${STAGE1_DICT_LOSS_WARMUP_EPOCHS}"
  --stage1_commitment_loss_weight "${STAGE1_COMMITMENT_LOSS_WEIGHT}"
  --stage1_commitment_loss_weight_start "${STAGE1_COMMITMENT_LOSS_WEIGHT_START}"
  --stage1_commitment_loss_warmup_epochs "${STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS}"
  --stage1_amp "${STAGE1_AMP}"
  --stage1_amp_dtype "${STAGE1_AMP_DTYPE}"
  --stage1_coherence_weight "${STAGE1_COHERENCE_WEIGHT}"
  --stage1_coherence_weight_start "${STAGE1_COHERENCE_WEIGHT_START}"
  --stage1_coherence_warmup_epochs "${STAGE1_COHERENCE_WARMUP_EPOCHS}"
  --stage1_coherence_margin "${STAGE1_COHERENCE_MARGIN}"
  --stage2_warmup_steps "${STAGE2_WARMUP_STEPS}"
  --stage2_min_lr_ratio "${STAGE2_MIN_LR_RATIO}"
  --stage2_weight_decay "${STAGE2_WEIGHT_DECAY}"
  --stage2_sched_sampling_final_prob "${STAGE2_SCHED_SAMPLING_FINAL_PROB}"
  --stage2_coeff_loss_type "${STAGE2_COEFF_LOSS_TYPE}"
  --num_workers "${NUM_WORKERS}"
  --token_num_workers "${TOKEN_NUM_WORKERS}"
  --batch_size "${BATCH_SIZE}"
  --stage2_batch_size "${STAGE2_BATCH_SIZE}"
  --ae_num_downsamples "${AE_NUM_DOWNSAMPLES}"
  --embedding_dim "${EMBEDDING_DIM}"
  --num_hiddens "${NUM_HIDDENS}"
  --num_res_hiddens "${NUM_RES_HIDDENS}"
  --num_res_layers "${NUM_RES_LAYERS}"
  --num_atoms "${NUM_ATOMS}"
  --sparsity_level "${SPARSITY_LEVEL}"
  --n_bins "${N_BINS}"
  --commitment_cost "${COMMITMENT_COST}"
  --coef_max "${COEF_MAX}"
  --coef_quantization "${COEF_QUANTIZATION}"
  --coef_mu "${COEF_MU}"
  --patch_size "${PATCH_SIZE}"
  --patch_stride "${PATCH_STRIDE}"
  --patch_reconstruction "${PATCH_RECONSTRUCTION}"
  --stage2_arch "${STAGE2_ARCH}"
  --tf_d_model "${TF_D_MODEL}"
  --tf_heads "${TF_HEADS}"
  --tf_layers "${TF_LAYERS}"
  --tf_ff "${TF_FF}"
  --tf_dropout "${TF_DROPOUT}"
  --tf_global_tokens "${TF_GLOBAL_TOKENS}"
  --token_subset "${TOKEN_SUBSET}"
  --rfid_num_samples "${RFID_NUM_SAMPLES}"
  --stage2_fid_num_samples "${STAGE2_FID_NUM_SAMPLES}"
  --stage2_fid_every_epochs "${STAGE2_FID_EVERY_EPOCHS}"
  --wandb_mode "${WANDB_MODE}"
  --wandb_project "${WANDB_PROJECT}"
  --wandb_name "${WANDB_NAME}"
  --stage2_sample_every_steps "${STAGE2_SAMPLE_EVERY_STEPS}"
  --stage2_sample_batch_size "${STAGE2_SAMPLE_BATCH_SIZE}"
  --stage2_sample_candidate_factor "${STAGE2_SAMPLE_CANDIDATE_FACTOR}"
  --stage2_sample_temperature "${STAGE2_SAMPLE_TEMPERATURE}"
  --stage2_sample_top_k "${STAGE2_SAMPLE_TOP_K}"
  --stage2_sample_coeff_temperature "${STAGE2_SAMPLE_COEFF_TEMPERATURE}"
  --stage2_sample_coeff_mode "${STAGE2_SAMPLE_COEFF_MODE}"
  --stage2_sample_quality_weight "${STAGE2_SAMPLE_QUALITY_WEIGHT}"
  --stage2_sample_brightness_weight "${STAGE2_SAMPLE_BRIGHTNESS_WEIGHT}"
  --stage2_sample_overbright_weight "${STAGE2_SAMPLE_OVERBRIGHT_WEIGHT}"
  --stage2_sample_reject_dark_z "${STAGE2_SAMPLE_REJECT_DARK_Z}"
  --stage2_sample_reject_bright_z "${STAGE2_SAMPLE_REJECT_BRIGHT_Z}"
  --stage2_sample_image_size "${STAGE2_SAMPLE_IMAGE_SIZE}"
  --quantize_sparse_coeffs "${QUANTIZE_SPARSE_COEFFS}"
  --variational_coeffs "${VARIATIONAL_COEFFS}"
  --variational_coeff_kl_weight "${VARIATIONAL_COEFF_KL_WEIGHT}"
  --variational_coeff_prior_std "${VARIATIONAL_COEFF_PRIOR_STD}"
  --variational_coeff_min_std "${VARIATIONAL_COEFF_MIN_STD}"
)
if [[ -n "${STAGE1_SOURCE_CKPT}" ]]; then
  CMD+=(--stage1_source_ckpt "${STAGE1_SOURCE_CKPT}")
fi
if [[ -n "${STAGE2_SOURCE_RUN}" ]]; then
  CMD+=(--stage2_source_run "${STAGE2_SOURCE_RUN}")
fi
if [[ -n "${STAGE2_SOURCE_TOKEN_CACHE}" ]]; then
  CMD+=(--stage2_source_token_cache "${STAGE2_SOURCE_TOKEN_CACHE}")
fi
if [[ -n "${STAGE2_SOURCE_CKPT}" ]]; then
  CMD+=(--stage2_source_ckpt "${STAGE2_SOURCE_CKPT}")
fi
if [[ "${STAGE1_AUTO_RESUME_FROM_LATEST}" == "1" || "${STAGE1_AUTO_RESUME_FROM_LATEST}" == "true" || "${STAGE1_AUTO_RESUME_FROM_LATEST}" == "TRUE" || "${STAGE1_AUTO_RESUME_FROM_LATEST}" == "yes" || "${STAGE1_AUTO_RESUME_FROM_LATEST}" == "YES" ]]; then
  CMD+=(--stage1_auto_resume_from_latest)
fi
if [[ "${PATCH_BASED}" == "1" || "${PATCH_BASED}" == "true" || "${PATCH_BASED}" == "TRUE" || "${PATCH_BASED}" == "yes" || "${PATCH_BASED}" == "YES" ]]; then
  CMD+=(--patch_based)
fi
if [[ "${REBUILD_TOKEN_CACHE}" == "1" || "${REBUILD_TOKEN_CACHE}" == "true" || "${REBUILD_TOKEN_CACHE}" == "TRUE" || "${REBUILD_TOKEN_CACHE}" == "yes" || "${REBUILD_TOKEN_CACHE}" == "YES" ]]; then
  CMD+=(--rebuild_token_cache)
fi
if [[ "${STAGE2_AUTOREGRESSIVE_COEFFS}" == "1" || "${STAGE2_AUTOREGRESSIVE_COEFFS}" == "true" || "${STAGE2_AUTOREGRESSIVE_COEFFS}" == "TRUE" || "${STAGE2_AUTOREGRESSIVE_COEFFS}" == "yes" || "${STAGE2_AUTOREGRESSIVE_COEFFS}" == "YES" ]]; then
  CMD+=(--stage2_autoregressive_coeffs)
else
  CMD+=(--no_stage2_autoregressive_coeffs)
fi
if [[ "${STAGE2_SAMPLE_SORT_BY_QUALITY}" == "1" || "${STAGE2_SAMPLE_SORT_BY_QUALITY}" == "true" || "${STAGE2_SAMPLE_SORT_BY_QUALITY}" == "TRUE" || "${STAGE2_SAMPLE_SORT_BY_QUALITY}" == "yes" || "${STAGE2_SAMPLE_SORT_BY_QUALITY}" == "YES" ]]; then
  CMD+=(--stage2_sample_sort_by_quality)
else
  CMD+=(--no_stage2_sample_sort_by_quality)
fi
exec "\${CMD[@]}"
EOF_RUNNER
chmod +x "$RUNNER"
srun --nodes="$SLURM_NNODES" --ntasks="$SLURM_NNODES" --ntasks-per-node=1 nvidia-smi
srun --ntasks-per-node='"$GPUS_PER_NODE"' --gpus-per-task=1 singularity exec --nv \
  --bind "$PROJECT_DIR" \
  --bind "/scratch/$USER_NAME" \
  --bind "$DATA_DIR" \
  --bind "$OUT_DIR" \
  "$IMAGE" \
  bash "$RUNNER"'
