#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export ENTRYPOINT="${ENTRYPOINT:-laser.py}"

export PARTITION="${PARTITION:-gpu}"
export NODES="${NODES:-1}"
export GPUS_PER_NODE="${GPUS_PER_NODE:-3}"
export CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
export MEM_MB="${MEM_MB:-128000}"
export TIME_LIMIT="${TIME_LIMIT:-24:00:00}"

export DATA_DIR="${DATA_DIR:-/cache/home/xl598/Projects/data/celeba}"
export IMAGE_SIZE="${IMAGE_SIZE:-128}"
export OUT_DIR="${OUT_DIR:-/scratch/$USER/runs/laser_100ep}"

export STAGE1_EPOCHS="${STAGE1_EPOCHS:-100}"
export STAGE2_EPOCHS="${STAGE2_EPOCHS:-100}"
export STAGE1_AUTO_RESUME_FROM_LATEST="${STAGE1_AUTO_RESUME_FROM_LATEST:-false}"
export STAGE1_CHECKPOINT_EVERY_STEPS="${STAGE1_CHECKPOINT_EVERY_STEPS:-0}"

export STAGE1_LR="${STAGE1_LR:-2e-4}"
export STAGE2_LR="${STAGE2_LR:-1e-3}"
export STAGE1_LR_SCHEDULE="${STAGE1_LR_SCHEDULE:-cosine}"
export STAGE1_WARMUP_EPOCHS="${STAGE1_WARMUP_EPOCHS:-2}"
export STAGE1_MIN_LR_RATIO="${STAGE1_MIN_LR_RATIO:-0.1}"
export STAGE1_DICT_OPTIMIZER="${STAGE1_DICT_OPTIMIZER:-separate_sgd}"
export STAGE1_DICT_LR_MULTIPLIER="${STAGE1_DICT_LR_MULTIPLIER:-0.25}"
export STAGE1_DICT_LR_SCHEDULE="${STAGE1_DICT_LR_SCHEDULE:-cosine}"
export STAGE1_DICT_WARMUP_EPOCHS="${STAGE1_DICT_WARMUP_EPOCHS:-2}"
export STAGE1_DICT_MIN_LR_RATIO="${STAGE1_DICT_MIN_LR_RATIO:-0.05}"
export STAGE1_DICT_GRAD_CLIP="${STAGE1_DICT_GRAD_CLIP:-0.05}"
export STAGE1_DICT_MAX_UPDATE_NORM="${STAGE1_DICT_MAX_UPDATE_NORM:-0.0}"
export STAGE1_LOSS_SPIKE_SKIP_RATIO="${STAGE1_LOSS_SPIKE_SKIP_RATIO:-0.0}"
export STAGE1_LOSS_EMA_BETA="${STAGE1_LOSS_EMA_BETA:-0.98}"
export BOTTLENECK_WEIGHT="${BOTTLENECK_WEIGHT:-1.0}"
export GRAD_CLIP="${GRAD_CLIP:-1.0}"
export STAGE1_BOTTLENECK_WEIGHT_START="${STAGE1_BOTTLENECK_WEIGHT_START:-1.0}"
export STAGE1_BOTTLENECK_WARMUP_EPOCHS="${STAGE1_BOTTLENECK_WARMUP_EPOCHS:-0}"
export STAGE1_DICT_LOSS_WEIGHT="${STAGE1_DICT_LOSS_WEIGHT:-nan}"
export STAGE1_DICT_LOSS_WEIGHT_START="${STAGE1_DICT_LOSS_WEIGHT_START:-nan}"
export STAGE1_DICT_LOSS_WARMUP_EPOCHS="${STAGE1_DICT_LOSS_WARMUP_EPOCHS:-0}"
export STAGE1_COMMITMENT_LOSS_WEIGHT="${STAGE1_COMMITMENT_LOSS_WEIGHT:-nan}"
export STAGE1_COMMITMENT_LOSS_WEIGHT_START="${STAGE1_COMMITMENT_LOSS_WEIGHT_START:-nan}"
export STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS="${STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS:-0}"
export STAGE1_COHERENCE_WEIGHT="${STAGE1_COHERENCE_WEIGHT:-0.0}"
export STAGE1_COHERENCE_WEIGHT_START="${STAGE1_COHERENCE_WEIGHT_START:-nan}"
export STAGE1_COHERENCE_WARMUP_EPOCHS="${STAGE1_COHERENCE_WARMUP_EPOCHS:-0}"
export STAGE1_COHERENCE_MARGIN="${STAGE1_COHERENCE_MARGIN:-0.0}"

export STAGE2_WARMUP_STEPS="${STAGE2_WARMUP_STEPS:-500}"
export STAGE2_MIN_LR_RATIO="${STAGE2_MIN_LR_RATIO:-0.01}"
export STAGE2_WEIGHT_DECAY="${STAGE2_WEIGHT_DECAY:-0.01}"

export BATCH_SIZE="${BATCH_SIZE:-32}"
export STAGE2_BATCH_SIZE="${STAGE2_BATCH_SIZE:-32}"
export NUM_WORKERS="${NUM_WORKERS:-8}"
export TOKEN_NUM_WORKERS="${TOKEN_NUM_WORKERS:-4}"
export TOKEN_SUBSET="${TOKEN_SUBSET:-98304}"
export STAGE2_SAMPLE_EVERY_STEPS="${STAGE2_SAMPLE_EVERY_STEPS:-1000}"
export STAGE2_SAMPLE_BATCH_SIZE="${STAGE2_SAMPLE_BATCH_SIZE:-32}"
export STAGE2_SAMPLE_IMAGE_SIZE="${STAGE2_SAMPLE_IMAGE_SIZE:-$IMAGE_SIZE}"
export QUANTIZE_SPARSE_COEFFS="${QUANTIZE_SPARSE_COEFFS:-true}"

export AE_NUM_DOWNSAMPLES="${AE_NUM_DOWNSAMPLES:-4}"
export EMBEDDING_DIM="${EMBEDDING_DIM:-16}"
export NUM_HIDDENS="${NUM_HIDDENS:-64}"
export NUM_RES_HIDDENS="${NUM_RES_HIDDENS:-32}"
export NUM_RES_LAYERS="${NUM_RES_LAYERS:-1}"
export NUM_ATOMS="${NUM_ATOMS:-1024}"
export SPARSITY_LEVEL="${SPARSITY_LEVEL:-8}"
export N_BINS="${N_BINS:-256}"
export COMMITMENT_COST="${COMMITMENT_COST:-0.25}"
export COEF_MAX="${COEF_MAX:-3.0}"
export COEF_QUANTIZATION="${COEF_QUANTIZATION:-uniform}"
export COEF_MU="${COEF_MU:-0.0}"
export PATCH_BASED="${PATCH_BASED:-false}"
export PATCH_SIZE="${PATCH_SIZE:-4}"
export PATCH_STRIDE="${PATCH_STRIDE:-2}"
export PATCH_RECONSTRUCTION="${PATCH_RECONSTRUCTION:-center_crop}"

if [[ -z "${STAGE2_COEFF_LOSS_TYPE+x}" ]]; then
  if [[ "${VARIATIONAL_COEFFS:-false}" == "1" || "${VARIATIONAL_COEFFS:-false}" == "true" || "${VARIATIONAL_COEFFS:-false}" == "TRUE" || "${VARIATIONAL_COEFFS:-false}" == "yes" || "${VARIATIONAL_COEFFS:-false}" == "YES" ]]; then
    export STAGE2_COEFF_LOSS_TYPE="gaussian_nll"
  elif [[ "${PATCH_BASED}" == "1" || "${PATCH_BASED}" == "true" || "${PATCH_BASED}" == "TRUE" || "${PATCH_BASED}" == "yes" || "${PATCH_BASED}" == "YES" ]]; then
    export STAGE2_COEFF_LOSS_TYPE="mse"
  elif [[ "${QUANTIZE_SPARSE_COEFFS}" == "0" || "${QUANTIZE_SPARSE_COEFFS}" == "false" || "${QUANTIZE_SPARSE_COEFFS}" == "FALSE" || "${QUANTIZE_SPARSE_COEFFS}" == "no" || "${QUANTIZE_SPARSE_COEFFS}" == "NO" ]]; then
    export STAGE2_COEFF_LOSS_TYPE="mse"
  else
    export STAGE2_COEFF_LOSS_TYPE="gt_atom_recon_mse"
  fi
else
  export STAGE2_COEFF_LOSS_TYPE="${STAGE2_COEFF_LOSS_TYPE}"
fi

export WANDB_MODE="${WANDB_MODE:-online}"
export WANDB_PROJECT="${WANDB_PROJECT:-laser-dl}"
export WANDB_NAME="${WANDB_NAME:-laser100}"
export LOG_PREFIX="${LOG_PREFIX:-laser100}"
export JOB_NAME="${JOB_NAME:-laser-100}"

PACKED_NPY="$DATA_DIR/celeba_${IMAGE_SIZE}x${IMAGE_SIZE}_rgb_uint8.npy"
if [[ -L "$PACKED_NPY" ]]; then
  echo "Warning: $PACKED_NPY is a symlink; some nodes have fallen back to the raw image tree in this setup." >&2
  echo "Prefer a real file under DATA_DIR for the packed fast path." >&2
fi

exec "$ROOT_DIR/scripts/launch_proto_rqsd_multinode_slurm.sh"
