#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PARTITION="${PARTITION:-gpu-redhat}"
NODES="${NODES:-8}"
GPUS_PER_NODE="${GPUS_PER_NODE:-3}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
MEM_MB="${MEM_MB:-500000}"
TIME_LIMIT="${TIME_LIMIT:-3-00:00:00}"

STAGE1_EPOCHS="${STAGE1_EPOCHS:-100}"
STAGE2_EPOCHS="${STAGE2_EPOCHS:-100}"
STAGE1_LR="${STAGE1_LR:-2e-4}"
STAGE2_LR="${STAGE2_LR:-1e-3}"
STAGE1_WARMUP_EPOCHS="${STAGE1_WARMUP_EPOCHS:-2}"
STAGE1_MIN_LR_RATIO="${STAGE1_MIN_LR_RATIO:-0.1}"
STAGE1_DICT_OPTIMIZER="${STAGE1_DICT_OPTIMIZER:-separate_sgd}"
STAGE1_DICT_LR_MULTIPLIER="${STAGE1_DICT_LR_MULTIPLIER:-0.25}"
STAGE1_DICT_LR_SCHEDULE="${STAGE1_DICT_LR_SCHEDULE:-cosine}"
STAGE1_DICT_WARMUP_EPOCHS="${STAGE1_DICT_WARMUP_EPOCHS:-2}"
STAGE1_DICT_MIN_LR_RATIO="${STAGE1_DICT_MIN_LR_RATIO:-0.05}"
STAGE1_DICT_GRAD_CLIP="${STAGE1_DICT_GRAD_CLIP:-0.05}"
STAGE1_DICT_MAX_UPDATE_NORM="${STAGE1_DICT_MAX_UPDATE_NORM:-0.0}"
STAGE1_LOSS_SPIKE_SKIP_RATIO="${STAGE1_LOSS_SPIKE_SKIP_RATIO:-0.0}"
STAGE1_LOSS_EMA_BETA="${STAGE1_LOSS_EMA_BETA:-0.98}"
STAGE1_BOTTLENECK_WEIGHT_START="${STAGE1_BOTTLENECK_WEIGHT_START:-1.0}"
STAGE1_BOTTLENECK_WARMUP_EPOCHS="${STAGE1_BOTTLENECK_WARMUP_EPOCHS:-0}"
GRAD_CLIP="${GRAD_CLIP:-1.0}"

STAGE2_WARMUP_STEPS="${STAGE2_WARMUP_STEPS:-500}"
STAGE2_MIN_LR_RATIO="${STAGE2_MIN_LR_RATIO:-0.01}"
STAGE2_WEIGHT_DECAY="${STAGE2_WEIGHT_DECAY:-0.01}"

BATCH_SIZE="${BATCH_SIZE:-32}"
STAGE2_BATCH_SIZE="${STAGE2_BATCH_SIZE:-32}"
NUM_WORKERS="${NUM_WORKERS:-8}"
TOKEN_NUM_WORKERS="${TOKEN_NUM_WORKERS:-0}"

WANDB_MODE="${WANDB_MODE:-online}"
WANDB_PROJECT="${WANDB_PROJECT:-laser-scratch}"
WANDB_NAME="${WANDB_NAME:-proto_rqsd_rh_24g_100ep_dict_safe_ref}"
LOG_PREFIX="${LOG_PREFIX:-proto_rqsd_rh_24g_mn}"
JOB_NAME="${JOB_NAME:-proto-rqsd-rh-24g}"

export PARTITION NODES GPUS_PER_NODE CPUS_PER_TASK MEM_MB TIME_LIMIT
export STAGE1_EPOCHS STAGE2_EPOCHS STAGE1_LR STAGE2_LR
export STAGE1_WARMUP_EPOCHS STAGE1_MIN_LR_RATIO
export STAGE1_DICT_OPTIMIZER STAGE1_DICT_LR_MULTIPLIER STAGE1_DICT_LR_SCHEDULE
export STAGE1_DICT_WARMUP_EPOCHS STAGE1_DICT_MIN_LR_RATIO STAGE1_DICT_GRAD_CLIP
export STAGE1_DICT_MAX_UPDATE_NORM STAGE1_LOSS_SPIKE_SKIP_RATIO STAGE1_LOSS_EMA_BETA
export STAGE1_BOTTLENECK_WEIGHT_START STAGE1_BOTTLENECK_WARMUP_EPOCHS GRAD_CLIP
export STAGE2_WARMUP_STEPS STAGE2_MIN_LR_RATIO STAGE2_WEIGHT_DECAY
export BATCH_SIZE STAGE2_BATCH_SIZE NUM_WORKERS TOKEN_NUM_WORKERS
export WANDB_MODE WANDB_PROJECT WANDB_NAME LOG_PREFIX JOB_NAME

exec "$ROOT_DIR/scripts/launch_proto_rqsd_multinode_slurm.sh"
