#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DATA_DIR="${DATA_DIR:-/scratch/$USER/datasets/celebahq_packed_256}"
OUT_ROOT="${OUT_ROOT:-/scratch/$USER/runs/celebahq256_patch_stage2_param_sweep}"
PARTITION="${PARTITION:-gpu-redhat}"
NODES="${NODES:-1}"
GPUS_PER_NODE="${GPUS_PER_NODE:-2}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
MEM_MB="${MEM_MB:-128000}"
TIME_LIMIT="${TIME_LIMIT:-3-00:00:00}"

ENTRYPOINT="${ENTRYPOINT:-proto.py}"
IMAGE_SIZE="${IMAGE_SIZE:-256}"
STAGE1_EPOCHS="${STAGE1_EPOCHS:-0}"
STAGE2_EPOCHS="${STAGE2_EPOCHS:-20}"
BATCH_SIZE="${BATCH_SIZE:-6}"
NUM_WORKERS="${NUM_WORKERS:-8}"
TOKEN_NUM_WORKERS="${TOKEN_NUM_WORKERS:-4}"

WANDB_MODE="${WANDB_MODE:-online}"
WANDB_PROJECT="${WANDB_PROJECT:-laser-dl}"
RUN_PREFIX="${RUN_PREFIX:-celebahq256_s2param20}"
JOB_PREFIX="${JOB_PREFIX:-chq256-s2p}"
CASE_FILTER="${CASE_FILTER:-}"

NUM_ATOMS="${NUM_ATOMS:-4096}"
SPARSITY_LEVEL="${SPARSITY_LEVEL:-16}"
PATCH_SIZE="${PATCH_SIZE:-8}"
PATCH_STRIDE="${PATCH_STRIDE:-4}"
N_BINS="${N_BINS:-256}"
COEF_MAX="${COEF_MAX:-8.0}"
PATCH_RECONSTRUCTION="${PATCH_RECONSTRUCTION:-hann}"
QUANTIZE_SPARSE_COEFFS="${QUANTIZE_SPARSE_COEFFS:-false}"
AE_NUM_DOWNSAMPLES="${AE_NUM_DOWNSAMPLES:-2}"
NUM_HIDDENS="${NUM_HIDDENS:-64}"
NUM_RES_HIDDENS="${NUM_RES_HIDDENS:-32}"
NUM_RES_LAYERS="${NUM_RES_LAYERS:-1}"

SOURCE_RUN_DIR="${SOURCE_RUN_DIR:-/scratch/xl598/runs/celebahq256_20ep_matrix_sweep_20260321_102309/celebahq256_m20_patch_r_p8s4_e16_a4096_k16/20260321_102327}"
STAGE1_SOURCE_CKPT="${STAGE1_SOURCE_CKPT:-$SOURCE_RUN_DIR/stage1/ae_best.pt}"
STAGE2_SOURCE_TOKEN_CACHE="${STAGE2_SOURCE_TOKEN_CACHE:-$SOURCE_RUN_DIR/stage2/tokens_cache.pt}"

STAGE2_SAMPLE_EVERY_STEPS="${STAGE2_SAMPLE_EVERY_STEPS:-5000}"
STAGE2_SAMPLE_BATCH_SIZE="${STAGE2_SAMPLE_BATCH_SIZE:-8}"
STAGE2_SAMPLE_CANDIDATE_FACTOR="${STAGE2_SAMPLE_CANDIDATE_FACTOR:-8}"
STAGE2_SAMPLE_TEMPERATURE="${STAGE2_SAMPLE_TEMPERATURE:-0.16}"
STAGE2_SAMPLE_TOP_K="${STAGE2_SAMPLE_TOP_K:-48}"
STAGE2_SAMPLE_COEFF_MODE="${STAGE2_SAMPLE_COEFF_MODE:-mean}"
STAGE2_SAMPLE_COEFF_TEMPERATURE="${STAGE2_SAMPLE_COEFF_TEMPERATURE:-nan}"
STAGE2_SAMPLE_QUALITY_WEIGHT="${STAGE2_SAMPLE_QUALITY_WEIGHT:-1.0}"
STAGE2_SAMPLE_BRIGHTNESS_WEIGHT="${STAGE2_SAMPLE_BRIGHTNESS_WEIGHT:-2.0}"
STAGE2_SAMPLE_OVERBRIGHT_WEIGHT="${STAGE2_SAMPLE_OVERBRIGHT_WEIGHT:-2.0}"
STAGE2_SAMPLE_REJECT_DARK_Z="${STAGE2_SAMPLE_REJECT_DARK_Z:-1.0}"
STAGE2_SAMPLE_REJECT_BRIGHT_Z="${STAGE2_SAMPLE_REJECT_BRIGHT_Z:-1.0}"
STAGE2_SAMPLE_SORT_BY_QUALITY="${STAGE2_SAMPLE_SORT_BY_QUALITY:-true}"
STAGE2_SAMPLE_IMAGE_SIZE="${STAGE2_SAMPLE_IMAGE_SIZE:-$IMAGE_SIZE}"
RFID_NUM_SAMPLES="${RFID_NUM_SAMPLES:-0}"
STAGE2_FID_NUM_SAMPLES="${STAGE2_FID_NUM_SAMPLES:-128}"
STAGE2_FID_EVERY_EPOCHS="${STAGE2_FID_EVERY_EPOCHS:-5}"

if [[ ! -d "$DATA_DIR" ]]; then
  echo "Missing data directory: $DATA_DIR" >&2
  exit 1
fi
if [[ ! -f "$STAGE1_SOURCE_CKPT" ]]; then
  echo "Missing stage-1 source checkpoint: $STAGE1_SOURCE_CKPT" >&2
  exit 1
fi
if [[ ! -f "$STAGE2_SOURCE_TOKEN_CACHE" ]]; then
  echo "Missing stage-2 source token cache: $STAGE2_SOURCE_TOKEN_CACHE" >&2
  exit 1
fi

mkdir -p "$OUT_ROOT"

cases=(
  "baseline|32|1e-3|512|8|12|1024|0|0.00|0.01|true"
  "lowlr_sched10|32|6e-4|512|8|12|1024|0|0.10|0.01|true"
  "wide768_g8|16|8e-4|768|12|12|1536|8|0.10|0.01|true"
  "supportonly_wide768_g8|16|8e-4|768|12|12|1536|8|0.10|0.01|false"
)

CASE_FILTER="${CASE_FILTER// /}"
submitted=0

for case_spec in "${cases[@]}"; do
  IFS='|' read -r case_name stage2_batch_size stage2_lr tf_d_model tf_heads tf_layers tf_ff tf_global_tokens sched_prob stage2_weight_decay autoregressive_coeffs <<< "$case_spec"

  if [[ -n "$CASE_FILTER" && ",$CASE_FILTER," != *",$case_name,"* ]]; then
    continue
  fi

  run_name="${RUN_PREFIX}_${case_name}_p${PATCH_SIZE}s${PATCH_STRIDE}_a${NUM_ATOMS}_k${SPARSITY_LEVEL}"
  job_name="${JOB_PREFIX}-${case_name}"
  out_dir="$OUT_ROOT/$run_name"

  echo "[Sweep] submitting $run_name"
  submit_output="$(
    PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" \
    DATA_DIR="$DATA_DIR" \
    OUT_DIR="$out_dir" \
    PARTITION="$PARTITION" \
    NODES="$NODES" \
    GPUS_PER_NODE="$GPUS_PER_NODE" \
    CPUS_PER_TASK="$CPUS_PER_TASK" \
    MEM_MB="$MEM_MB" \
    TIME_LIMIT="$TIME_LIMIT" \
    ENTRYPOINT="$ENTRYPOINT" \
    IMAGE_SIZE="$IMAGE_SIZE" \
    STAGE1_EPOCHS="$STAGE1_EPOCHS" \
    STAGE2_EPOCHS="$STAGE2_EPOCHS" \
    BATCH_SIZE="$BATCH_SIZE" \
    STAGE2_BATCH_SIZE="$stage2_batch_size" \
    NUM_WORKERS="$NUM_WORKERS" \
    TOKEN_NUM_WORKERS="$TOKEN_NUM_WORKERS" \
    WANDB_MODE="$WANDB_MODE" \
    WANDB_PROJECT="$WANDB_PROJECT" \
    WANDB_NAME="$run_name" \
    LOG_PREFIX="$run_name" \
    JOB_NAME="$job_name" \
    NUM_ATOMS="$NUM_ATOMS" \
    SPARSITY_LEVEL="$SPARSITY_LEVEL" \
    N_BINS="$N_BINS" \
    COEF_MAX="$COEF_MAX" \
    QUANTIZE_SPARSE_COEFFS="$QUANTIZE_SPARSE_COEFFS" \
    AE_NUM_DOWNSAMPLES="$AE_NUM_DOWNSAMPLES" \
    NUM_HIDDENS="$NUM_HIDDENS" \
    NUM_RES_HIDDENS="$NUM_RES_HIDDENS" \
    NUM_RES_LAYERS="$NUM_RES_LAYERS" \
    PATCH_SIZE="$PATCH_SIZE" \
    PATCH_STRIDE="$PATCH_STRIDE" \
    PATCH_RECONSTRUCTION="$PATCH_RECONSTRUCTION" \
    STAGE1_SOURCE_CKPT="$STAGE1_SOURCE_CKPT" \
    STAGE2_SOURCE_TOKEN_CACHE="$STAGE2_SOURCE_TOKEN_CACHE" \
    STAGE2_LR="$stage2_lr" \
    STAGE2_WEIGHT_DECAY="$stage2_weight_decay" \
    STAGE2_SCHED_SAMPLING_FINAL_PROB="$sched_prob" \
    TF_D_MODEL="$tf_d_model" \
    TF_HEADS="$tf_heads" \
    TF_LAYERS="$tf_layers" \
    TF_FF="$tf_ff" \
    TF_GLOBAL_TOKENS="$tf_global_tokens" \
    STAGE2_AUTOREGRESSIVE_COEFFS="$autoregressive_coeffs" \
    STAGE2_SAMPLE_EVERY_STEPS="$STAGE2_SAMPLE_EVERY_STEPS" \
    STAGE2_SAMPLE_BATCH_SIZE="$STAGE2_SAMPLE_BATCH_SIZE" \
    STAGE2_SAMPLE_CANDIDATE_FACTOR="$STAGE2_SAMPLE_CANDIDATE_FACTOR" \
    STAGE2_SAMPLE_TEMPERATURE="$STAGE2_SAMPLE_TEMPERATURE" \
    STAGE2_SAMPLE_TOP_K="$STAGE2_SAMPLE_TOP_K" \
    STAGE2_SAMPLE_COEFF_MODE="$STAGE2_SAMPLE_COEFF_MODE" \
    STAGE2_SAMPLE_COEFF_TEMPERATURE="$STAGE2_SAMPLE_COEFF_TEMPERATURE" \
    STAGE2_SAMPLE_QUALITY_WEIGHT="$STAGE2_SAMPLE_QUALITY_WEIGHT" \
    STAGE2_SAMPLE_BRIGHTNESS_WEIGHT="$STAGE2_SAMPLE_BRIGHTNESS_WEIGHT" \
    STAGE2_SAMPLE_OVERBRIGHT_WEIGHT="$STAGE2_SAMPLE_OVERBRIGHT_WEIGHT" \
    STAGE2_SAMPLE_REJECT_DARK_Z="$STAGE2_SAMPLE_REJECT_DARK_Z" \
    STAGE2_SAMPLE_REJECT_BRIGHT_Z="$STAGE2_SAMPLE_REJECT_BRIGHT_Z" \
    STAGE2_SAMPLE_SORT_BY_QUALITY="$STAGE2_SAMPLE_SORT_BY_QUALITY" \
    STAGE2_SAMPLE_IMAGE_SIZE="$STAGE2_SAMPLE_IMAGE_SIZE" \
    RFID_NUM_SAMPLES="$RFID_NUM_SAMPLES" \
    STAGE2_FID_NUM_SAMPLES="$STAGE2_FID_NUM_SAMPLES" \
    STAGE2_FID_EVERY_EPOCHS="$STAGE2_FID_EVERY_EPOCHS" \
    "$ROOT_DIR/scripts/patch_celebahq256_best.sh"
  )"
  printf '%s\n' "$submit_output"
  submitted=$((submitted + 1))
done

if ((submitted == 0)); then
  echo "No cases matched CASE_FILTER=$CASE_FILTER" >&2
  exit 1
fi
