#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export OUT_DIR="${OUT_DIR:-/cache/home/$USER/runs/laser_patch100}"
export WANDB_NAME="${WANDB_NAME:-patch100}"
export LOG_PREFIX="${LOG_PREFIX:-patch100}"
export JOB_NAME="${JOB_NAME:-laser-patch100}"

export AE_NUM_DOWNSAMPLES="${AE_NUM_DOWNSAMPLES:-2}"
export NUM_ATOMS="${NUM_ATOMS:-3072}"
export SPARSITY_LEVEL="${SPARSITY_LEVEL:-16}"
export STAGE1_WARMUP_EPOCHS="${STAGE1_WARMUP_EPOCHS:-1}"
export STAGE1_DICT_OPTIMIZER="${STAGE1_DICT_OPTIMIZER:-shared_adam}"
export STAGE1_DICT_LR_MULTIPLIER="${STAGE1_DICT_LR_MULTIPLIER:-1.0}"
export STAGE1_DICT_WARMUP_EPOCHS="${STAGE1_DICT_WARMUP_EPOCHS:-0}"
export STAGE1_DICT_GRAD_CLIP="${STAGE1_DICT_GRAD_CLIP:-1.0}"
export COMMITMENT_COST="${COMMITMENT_COST:-1.0}"
export QUANTIZE_SPARSE_COEFFS="${QUANTIZE_SPARSE_COEFFS:-false}"
export BOTTLENECK_WEIGHT="${BOTTLENECK_WEIGHT:-0.05}"
export STAGE1_BOTTLENECK_WEIGHT_START="${STAGE1_BOTTLENECK_WEIGHT_START:-0.25}"
export STAGE1_BOTTLENECK_WARMUP_EPOCHS="${STAGE1_BOTTLENECK_WARMUP_EPOCHS:-1}"
export STAGE1_DICT_LOSS_WEIGHT="${STAGE1_DICT_LOSS_WEIGHT:-0.01}"
export STAGE1_DICT_LOSS_WEIGHT_START="${STAGE1_DICT_LOSS_WEIGHT_START:-0.05}"
export STAGE1_DICT_LOSS_WARMUP_EPOCHS="${STAGE1_DICT_LOSS_WARMUP_EPOCHS:-12}"
export STAGE1_COMMITMENT_LOSS_WEIGHT="${STAGE1_COMMITMENT_LOSS_WEIGHT:-0.10}"
export STAGE1_COMMITMENT_LOSS_WEIGHT_START="${STAGE1_COMMITMENT_LOSS_WEIGHT_START:-0.25}"
export STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS="${STAGE1_COMMITMENT_LOSS_WARMUP_EPOCHS:-12}"
export STAGE1_COHERENCE_WEIGHT="${STAGE1_COHERENCE_WEIGHT:-1.0}"
export STAGE1_COHERENCE_WEIGHT_START="${STAGE1_COHERENCE_WEIGHT_START:-0.0}"
export STAGE1_COHERENCE_WARMUP_EPOCHS="${STAGE1_COHERENCE_WARMUP_EPOCHS:-12}"
export STAGE1_COHERENCE_MARGIN="${STAGE1_COHERENCE_MARGIN:-0.0}"
export PATCH_BASED="${PATCH_BASED:-true}"
export PATCH_SIZE="${PATCH_SIZE:-8}"
export PATCH_STRIDE="${PATCH_STRIDE:-4}"
export PATCH_RECONSTRUCTION="${PATCH_RECONSTRUCTION:-hann}"
export STAGE2_COEFF_LOSS_TYPE="${STAGE2_COEFF_LOSS_TYPE:-mse}"

case "${QUANTIZE_SPARSE_COEFFS,,}" in
  1|true|yes)
    export N_BINS="${N_BINS:-2048}"
    export COEF_MAX="${COEF_MAX:-20.0}"
    ;;
  *)
    export N_BINS="${N_BINS:-256}"
    export COEF_MAX="${COEF_MAX:-8.0}"
    ;;
esac

exec "$ROOT_DIR/scripts/launch_100ep.sh" "$@"
