defaults:
  - model: vqvae  # Default model type
  - _self_

seed: 42

data:
  path: "data/celeba"
  image_size: 64

training:
  batch_size: 64
  num_workers: 4
  max_epochs: 100
  learning_rate: 1e-4
  beta: 0.9
  accelerator: "gpu"
  devices: 1
  precision: 32
  gradient_clip_val: 1.0

checkpoint:
  dirpath: "checkpoints"
  filename: "model-{epoch:02d}-{val_loss:.2f}"
  save_top_k: 3

wandb:
  project: "vae-project"
  name: "experiment"
  save_dir: "wandb" 