#!/usr/bin/env bash
# CelebA-HQ d5 per-site K=3 quantized-token pipeline with gated adversarial
# stage-1 training.
#
# Follow-up to W&B run helloimlixin-rutgers/laser/knmu7amb:
# - replace p4/s4 patch sparse coding with per-site dictionary coding
# - increase stage-1 spatial compression to 256 -> 8x8 latents
# - keep attention at the low/mid resolutions and add the 8x8 attention level
# - delay PatchGAN until reconstruction MSE is below a configurable threshold
set -euo pipefail

cd /home/xl598/Projects/laser

STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)_d5_site_k3_adv}"
NUM_EMBEDDINGS="${NUM_EMBEDDINGS:-4096}"
RUN_ROOT="${RUN_ROOT:-/home/xl598/Projects/laser/runs/celebahq_d5_site_k3_a${NUM_EMBEDDINGS}_adv_quant_${STAMP}}"
PIPELINE_LOG="${PIPELINE_LOG:-${RUN_ROOT}/pipeline.nohup.log}"

mkdir -p "${RUN_ROOT}"

echo "[$(date --iso-8601=seconds)] launching d5 per-site K=3 gated adversarial quant pipeline"
echo "RUN_ROOT=${RUN_ROOT}"
echo "PIPELINE_LOG=${PIPELINE_LOG}"

exec env \
  STAMP="${STAMP}" \
  RUN_ROOT="${RUN_ROOT}" \
  WANDB_GROUP="celebahq_d5_site_k3_a${NUM_EMBEDDINGS}_adv_quant_${STAMP}" \
  IMAGE_SIZE=256 \
  STAGE1_DOWNSAMPLES=5 \
  STAGE1_CHANNEL_MULTIPLIERS="[1,1,2,2,4,4]" \
  STAGE1_ATTN_RESOLUTIONS="[8,16,32]" \
  PATCH_BASED=false \
  PATCH_SIZE=1 \
  PATCH_STRIDE=1 \
  SPARSITY_LEVEL=3 \
  NUM_EMBEDDINGS="${NUM_EMBEDDINGS}" \
  EMBEDDING_DIM="${EMBEDDING_DIM:-256}" \
  NUM_HIDDENS="${NUM_HIDDENS:-128}" \
  NUM_RESIDUAL_BLOCKS="${NUM_RESIDUAL_BLOCKS:-3}" \
  NUM_RESIDUAL_HIDDENS="${NUM_RESIDUAL_HIDDENS:-128}" \
  DECODER_EXTRA_RESIDUAL_LAYERS="${DECODER_EXTRA_RESIDUAL_LAYERS:-3}" \
  BACKBONE_LATENT_CHANNELS="${BACKBONE_LATENT_CHANNELS:-512}" \
  STAGE1_EPOCHS="${STAGE1_EPOCHS:-40}" \
  STAGE1_BATCH_SIZE="${STAGE1_BATCH_SIZE:-3}" \
  STAGE1_COMPUTE_FID="${STAGE1_COMPUTE_FID:-true}" \
  STAGE1_FID_FEATURE="${STAGE1_FID_FEATURE:-2048}" \
  RECON_MSE_WEIGHT="${RECON_MSE_WEIGHT:-0.25}" \
  RECON_L1_WEIGHT="${RECON_L1_WEIGHT:-1.0}" \
  RECON_EDGE_WEIGHT="${RECON_EDGE_WEIGHT:-0.50}" \
  BOTTLENECK_LOSS_WEIGHT="${BOTTLENECK_LOSS_WEIGHT:-0.25}" \
  COMMITMENT_COST="${COMMITMENT_COST:-0.05}" \
  COEF_MAX="${COEF_MAX:-16.0}" \
  COEFF_BINS="${COEFF_BINS:-256}" \
  PERCEPTUAL_WEIGHT="${PERCEPTUAL_WEIGHT:-0.20}" \
  PERCEPTUAL_START_STEP="${PERCEPTUAL_START_STEP:-1000}" \
  PERCEPTUAL_WARMUP_STEPS="${PERCEPTUAL_WARMUP_STEPS:-2000}" \
  ADVERSARIAL_WEIGHT="${ADVERSARIAL_WEIGHT:-0.03}" \
  ADVERSARIAL_START_STEP="${ADVERSARIAL_START_STEP:-24000}" \
  ADVERSARIAL_WARMUP_STEPS="${ADVERSARIAL_WARMUP_STEPS:-24000}" \
  ADVERSARIAL_START_RECON_MSE="${ADVERSARIAL_START_RECON_MSE:-0.018}" \
  ADVERSARIAL_QUALITY_EMA_DECAY="${ADVERSARIAL_QUALITY_EMA_DECAY:-0.99}" \
  DISCRIMINATOR_LR="${DISCRIMINATOR_LR:-5.0e-5}" \
  DISCRIMINATOR_CHANNELS="${DISCRIMINATOR_CHANNELS:-64}" \
  DISCRIMINATOR_LAYERS="${DISCRIMINATOR_LAYERS:-3}" \
  STAGE2_EPOCHS="${STAGE2_EPOCHS:-150}" \
  STAGE2_MAX_STEPS="${STAGE2_MAX_STEPS:-120000}" \
  STAGE2_BATCH_SIZE="${STAGE2_BATCH_SIZE:-8}" \
  STAGE2_COMPUTE_GENERATION_FID="${STAGE2_COMPUTE_GENERATION_FID:-true}" \
  STAGE2_GENERATION_METRIC_NUM_SAMPLES="${STAGE2_GENERATION_METRIC_NUM_SAMPLES:-256}" \
  STAGE2_SAVE_FINAL_SAMPLES_AFTER_FIT="${STAGE2_SAVE_FINAL_SAMPLES_AFTER_FIT:-true}" \
  STAGE2_RUN_TEST_AFTER_FIT="${STAGE2_RUN_TEST_AFTER_FIT:-false}" \
  bash scripts/run_celebahq_p2s2_k4_quant_pipeline.sh >"${PIPELINE_LOG}" 2>&1
