#!/usr/bin/env bash
# CelebA-HQ p2s2/k4/a4096 pipeline for reconstruction rFID and generation FID.
# Runs long adversarial stage-1 training before building the token cache, then
# trains a paper-scale transformer prior.
set -euo pipefail

cd /home/xl598/Projects/laser

STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)_p2s2k4_adv_rfid_fid}"
NUM_EMBEDDINGS="${NUM_EMBEDDINGS:-4096}"
RUN_ROOT="${RUN_ROOT:-/home/xl598/Projects/laser/runs/celebahq_p2s2_k4_a${NUM_EMBEDDINGS}_adv_rfid_fid_${STAMP}}"
PIPELINE_LOG="${PIPELINE_LOG:-${RUN_ROOT}/pipeline.nohup.log}"

mkdir -p "${RUN_ROOT}"

echo "[$(date --iso-8601=seconds)] launching p2s2/k4/a${NUM_EMBEDDINGS} adversarial rFID/FID pipeline"
echo "RUN_ROOT=${RUN_ROOT}"
echo "PIPELINE_LOG=${PIPELINE_LOG}"

exec env \
  STAMP="${STAMP}" \
  RUN_ROOT="${RUN_ROOT}" \
  WANDB_GROUP="celebahq_p2s2_k4_a${NUM_EMBEDDINGS}_adv_rfid_fid_${STAMP}" \
  NUM_EMBEDDINGS="${NUM_EMBEDDINGS}" \
  STAGE1_EPOCHS="${STAGE1_EPOCHS:-80}" \
  STAGE1_COMPUTE_FID=true \
  STAGE1_FID_FEATURE=2048 \
  PERCEPTUAL_WEIGHT="${PERCEPTUAL_WEIGHT:-0.20}" \
  PERCEPTUAL_START_STEP="${PERCEPTUAL_START_STEP:-1000}" \
  PERCEPTUAL_WARMUP_STEPS="${PERCEPTUAL_WARMUP_STEPS:-2000}" \
  ADVERSARIAL_WEIGHT="${ADVERSARIAL_WEIGHT:-0.05}" \
  ADVERSARIAL_START_STEP="${ADVERSARIAL_START_STEP:-30000}" \
  ADVERSARIAL_WARMUP_STEPS="${ADVERSARIAL_WARMUP_STEPS:-10000}" \
  ADVERSARIAL_START_RECON_MSE="${ADVERSARIAL_START_RECON_MSE:-0.03}" \
  DISCRIMINATOR_LR="${DISCRIMINATOR_LR:-5.0e-5}" \
  DISCRIMINATOR_CHANNELS="${DISCRIMINATOR_CHANNELS:-64}" \
  DISCRIMINATOR_LAYERS="${DISCRIMINATOR_LAYERS:-3}" \
  STAGE2_EPOCHS="${STAGE2_EPOCHS:-200}" \
  STAGE2_MAX_STEPS="${STAGE2_MAX_STEPS:--1}" \
  STAGE2_BATCH_SIZE="${STAGE2_BATCH_SIZE:-4}" \
  STAGE2_LR="${STAGE2_LR:-2.0e-4}" \
  STAGE2_WARMUP_STEPS="${STAGE2_WARMUP_STEPS:-2000}" \
  STAGE2_D_MODEL="${STAGE2_D_MODEL:-1024}" \
  STAGE2_N_HEADS="${STAGE2_N_HEADS:-16}" \
  STAGE2_N_LAYERS="${STAGE2_N_LAYERS:-24}" \
  STAGE2_D_FF="${STAGE2_D_FF:-4096}" \
  STAGE2_SAMPLE_EVERY_N_EPOCHS="${STAGE2_SAMPLE_EVERY_N_EPOCHS:-5}" \
  STAGE2_SAMPLE_TOP_K="${STAGE2_SAMPLE_TOP_K:-250}" \
  STAGE2_COMPUTE_GENERATION_FID=true \
  STAGE2_GENERATION_METRIC_NUM_SAMPLES="${STAGE2_GENERATION_METRIC_NUM_SAMPLES:-256}" \
  STAGE2_SAVE_FINAL_SAMPLES_AFTER_FIT=true \
  STAGE2_RUN_TEST_AFTER_FIT=false \
  bash scripts/run_celebahq_p2s2_k4_quant_pipeline.sh >"${PIPELINE_LOG}" 2>&1
